# -*- coding: utf-8 -*-
"""CADL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LygtZyoK1JDwQ_OKQ5rushfUGIVQFN5b
"""

# CADL2: Feature Extraction
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Dataset (restaurant reviews)
reviews = [
    "The food was absolutely delicious and fresh.",
    "I hated the service, it was very slow.",
    "The pasta was amazing, I loved it!",
    "The restaurant was too noisy and uncomfortable."
]

# --- Bag of Words ---
print("🔹 Bag of Words Representation")
bow_vectorizer = CountVectorizer()
X_bow = bow_vectorizer.fit_transform(reviews)
print(bow_vectorizer.get_feature_names_out())  # Vocabulary
print(X_bow.toarray())  # Sparse matrix converted to array

# --- TF-IDF ---
print("\n🔹 TF-IDF Representation")
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(reviews)
print(tfidf_vectorizer.get_feature_names_out())  # Vocabulary
print(X_tfidf.toarray())  # Sparse matrix converted to array