# -*- coding: utf-8 -*-
"""CADL3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWlNnBju49DVC_xvv1Gq_g40kzmCHYa8
"""



# CADL3: Named Entity Recognition with displacy
import spacy
from spacy import displacy
import pandas as pd

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")

# Example dataset: news headlines
news_text = """
Apple is planning to open a new campus in Bangalore next year.
Elon Musk gave a keynote at the Tesla conference in Berlin.
Amazon invested $4 billion in Anthropic, an AI startup.
"""

# Process text
doc = nlp(news_text)

# ---- 1. Display Named Entities in Text Output ----
print("🔹 Named Entities Found")
for ent in doc.ents:
    print(f"{ent.text:<20} --> {ent.label_}")

# ---- 2. Convert entities to DataFrame ----
ner_data = [(ent.text, ent.label_) for ent in doc.ents]
df = pd.DataFrame(ner_data, columns=["Entity", "Label"])

print("\nStructured DataFrame:\n")
print(df)

# ---- 3. Visualize Named Entities using displacy ----
# 'style="ent"' is used to highlight entities
print("\n🔹 Visualizing Named Entities...\n")
displacy.render(doc, style="ent", jupyter=True)